services:
  # Backend API - Node.js/Express
  api:
    build:
      context: ./backend/api
      dockerfile: .docker/Dockerfile
      target: ${WORK_MODE:-development}
    container_name: ${API_CONTAINER_NAME}
    ports:
      - ${API_HOST_PORT}:${API_PORT}
      - 5555:5555
    environment:
      - NODE_ENV=${WORK_MODE}
      - PORT=${API_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    volumes:
      - ./backend/api:/app
      - /app/node_modules
    networks:
      - juscash-net
    depends_on:
      - postgres
      - redis

  # Frontend - React com Vite
  vite:
    build:
      context: ./frontend
      dockerfile: .docker/Dockerfile
    container_name: ${VITE_CONTAINER_NAME}
    ports:
      - ${VITE_HOST_PORT}:${VITE_PORT}
    environment:
      - NODE_ENV=${WORK_MODE}
      - VITE_API_URL=${VITE_API_URL}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api
    networks:
      - juscash-net

  # Scraper - Python
  scraper:
    build:
      context: ./backend/scraper
      dockerfile: .docker/Dockerfile
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - POSTGRES_URL_ASYNC=${POSTGRES_URL_ASYNC}
    volumes:
      - ./backend/scraper:/app
    depends_on:
      - api
    networks:
      - juscash-net

  # Banco de dados PostgreSQL
  postgres:
    build:
      context: ./database/postgres
      dockerfile: .docker/Dockerfile
    container_name: ${POSTGRES_CONTAINER_NAME}
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_HOST_PORT}:${POSTGRES_PORT}
    volumes:
      - ./database/postgres/postgres-data:/var/lib/postgresql/data
      - ./database/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - juscash-net    
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "juscash_user", "-d", "juscash_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis para cache e filas
  redis:
    build:
      context: ./database/redis
      dockerfile: .docker/Dockerfile
    container_name: ${REDIS_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - ${REDIS_HOST_PORT}:${REDIS_PORT}
    volumes:
      - ./database/redis/redis-data:/var/lib/redis/data
      - ./database/redis/logs:/var/log/redis
    command: >
      sh -c "redis-server 
      --port ${REDIS_PORT} 
      --requirepass ${REDIS_PASSWORD}
      --dir /var/lib/redis/data
      --logfile /var/log/redis/redis.log
      --maxmemory 2gb
      --maxmemory-policy allkeys-lru
      --save '60 1'
      --appendfilename appendonly.aof
      --appendfsync everysec
      --bind 0.0.0.0
      --protected-mode no
      --maxclients 10000
      --tcp-keepalive 60"
    networks:
      - juscash-net
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 30s

volumes:
  postgres-data:
  redis-data:

networks:
  juscash-net:
    driver: bridge
