# docker-compose.scraper.yml
# Docker Compose específico para desenvolvimento do scraper
services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: dje-scraper
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=development
      # API Configuration
      - API_BASE_URL=http://host.docker.internal:8000
      - SCRAPER_API_KEY=${SCRAPER_API_KEY}
      - API_TIMEOUT=30
      # Browser Configuration
      - BROWSER_HEADLESS=true
      - BROWSER_TIMEOUT=30000
      # Scraper Configuration
      - SCRAPER_MAX_PAGES=5
      - LOG_LEVEL=DEBUG
    volumes:
      - .:/app
      - ./logs:/app/logs
    depends_on:
      - api
    networks:
      - juscash-net
    # Para desenvolvimento, não executar automaticamente
    command: ["tail", "-f", "/dev/null"]

networks:
  juscash-net:
    external: true